selector: SuperMemo2
user_decks:
  # The username 'default' is special, it is used when no user name is provided.
  - username: default
    decks:
      - name: Hex2Dec
        #cargo run --example generate_deck -- ./example_files/hex_dec_conversions.txt --output /tmp/hex.yaml
        path: /tmp/hex.yaml
      - name: Elaborate
        #cargo run --example generate_deck -- ./example_files/learnables_elaborate.yaml  --output /tmp/elaborate.yaml
        path: /tmp/elaborate.yaml

      - name: ElaborateWithCurve
        #cargo run --example generate_deck -- ./example_files/learnables_elaborate.yaml  --output /tmp/elaborate.yaml
        path: /tmp/elaborate.yaml
        selector: RecallCurveSelector
